# Generated by Django 4.1.1 on 2022-10-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productdetail_code_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='code_list',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
