# Generated by Django 4.1.1 on 2022-10-03 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_alter_productdetail_code_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificiacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Modelo base',
                'verbose_name_plural': 'Modelos base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOutput',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificiacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('reference', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=50)),
                ('name_client', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('price_total', models.PositiveIntegerField(default=0)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('output_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_output.outputtype')),
            ],
            options={
                'verbose_name': 'Modelo base',
                'verbose_name_plural': 'Modelos base',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OuputDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificiacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('quantity', models.IntegerField()),
                ('code_list', models.CharField(blank=True, default='', max_length=3000)),
                ('exit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_output.productoutput')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Modelo base',
                'verbose_name_plural': 'Modelos base',
                'abstract': False,
            },
        ),
    ]
