# Generated by Django 4.1.1 on 2022-10-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_output', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ouputdetail',
            options={'verbose_name': 'Detalle salida'},
        ),
        migrations.AlterModelOptions(
            name='outputtype',
            options={'verbose_name': 'Tipo de salida'},
        ),
        migrations.AlterModelOptions(
            name='productoutput',
            options={'verbose_name': 'Salida'},
        ),
        migrations.AddField(
            model_name='productoutput',
            name='invoice_number',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
