# Generated by Django 4.1.1 on 2022-10-12 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_productdetail_code_list'),
        ('product_output', '0003_alter_productoutput_invoice_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificiacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('quantity', models.IntegerField()),
                ('code_list', models.CharField(blank=True, default='', max_length=3000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Detalle salida',
            },
        ),
        migrations.AlterField(
            model_name='productoutput',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productoutput',
            name='reference',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='OuputDetail',
        ),
        migrations.AddField(
            model_name='outputdetail',
            name='product_output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_output.productoutput'),
        ),
    ]
