# Generated by Django 4.1.1 on 2022-10-15 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_output', '0004_outputdetail_alter_productoutput_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoutput',
            options={'ordering': ['-id'], 'verbose_name': 'Salida'},
        ),
    ]
