# Generated by Django 4.1.1 on 2022-10-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_alter_productdetail_code_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificiacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de prestamo',
            },
        ),
        migrations.CreateModel(
            name='ProductLoan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificiacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('identifier', models.CharField(max_length=50)),
                ('name_client', models.CharField(max_length=50)),
                ('in_wat', models.BooleanField(default=True)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_loan.loantype')),
            ],
            options={
                'verbose_name': 'Prestamo de producto',
                'verbose_name_plural': 'Prestamos de producto',
            },
        ),
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificiacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('quantity', models.IntegerField()),
                ('code_list', models.CharField(blank=True, default='', max_length=3000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('product_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_loan.productloan')),
            ],
            options={
                'verbose_name': 'Detalle de prestamo',
            },
        ),
    ]
