# Generated by Django 4.1 on 2022-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputdetail',
            options={'verbose_name': 'Detalle de entrada'},
        ),
        migrations.AddField(
            model_name='inputdetail',
            name='code_list',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='productinput',
            name='created_qr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productinput',
            name='image_qr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
